Repository hergetto/deepl_ex, pull requests merged in 2023-08, with the labels that each got.

#1 [Feature]: Add setup for elixir library
  .credo.exs
  .formatter.exs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/dependabot.yml
  .github/pr-title-checker-config.json
  .github/workflows/dependencies-workflow.yml
  .github/workflows/development-workflow.yml
  .github/workflows/linting-workflow.yml
  .github/workflows/main-workflow.yml
  .github/workflows/static-code-analysis-workflow.yml
  .github/workflows/unit-test-workflow.yml
  .gitignore
  LICENSE
  README.md
  coveralls.json
  lib/deepl_ex.ex
  mix.exs
  mix.lock
  priv/plts/.gitkeep
  test/deepl_ex_test.exs
  test/test_helper.exs
Labels: feature

#2 [Feature]: Create basic translation functionality
  README.md
  coveralls.json
  lib/deepl.ex
  lib/deepl_ex.ex
  lib/helpers/configuration.ex
  lib/helpers/language_validator.ex
  mix.exs
  mix.lock
  test/deepl_ex_test.exs
Labels: feature

#4 [Chore]: Release v0.1.0
  .credo.exs
  .formatter.exs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/dependabot.yml
  .github/pr-title-checker-config.json
  .github/workflows/dependencies-reusable.yml
  .github/workflows/development-workflow.yml
  .github/workflows/linting-reusable.yml
  .github/workflows/main-workflow.yml
  .github/workflows/publish-to-hex-reusable.yml
  .github/workflows/publish-workflow.yml
  .github/workflows/static-code-analysis-reusable.yml
  .github/workflows/unit-test-reusable.yml
  .gitignore
  CHANGELOG.md
  LICENSE
  README.md
  coveralls.json
  lib/deepl.ex
  lib/deepl_ex.ex
  lib/helpers/configuration.ex
  lib/helpers/language_validator.ex
  mix.exs
  mix.lock
  priv/plts/.gitkeep
  test/deepl_ex_test.exs
  test/test_helper.exs
Labels: release

#6 [Hotfix]: Remove organization from config
  CHANGELOG.md
  mix.exs
Labels: bug

#7 [Hotfix]: Remove organization from config
  CHANGELOG.md
  mix.exs
Labels: bug

#9 [Hotfix]: Invalid api key
  .github/workflows/publish-workflow.yml
Labels: bug

#10 [Hotfix]: Invalid api key
  .github/workflows/publish-workflow.yml
Labels: bug

#13 [Chore]: Release v0.1.1
  CHANGELOG.md
  README.md
  lib/deepl_ex.ex
  lib/helpers/configuration.ex
  mix.exs
Labels: release
